config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :petitions, only: [:index, :new, :create]

  namespace :admin do
    resources :petitions
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/petition.rb
class Petition < ApplicationRecord
  belongs_to :user

  def to_label
    "submitted by #{user.email} on #{created_at.to_date}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :petitions
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_current_admin!

  def authenticate_current_admin!
    if !current_user || !(current_user.is_admin?)
      flash[:alert] = "Not authorized"
      redirect_to petitions_path
    end
  end

end

app/controllers/admin/petitions_controller.rb
class Admin::PetitionsController < Admin::BaseController
  helper :hot_glue
  include HotGlue::ControllerHelper

  
  
  before_action :load_petition, only: [:show, :edit, :update, :destroy]
  after_action -> { flash.discard }, if: -> { request.format.symbol ==  :turbo_stream }



  

  



  def load_petition
    @petition = Petition.find(params[:id])
  end
  

  def load_all_petitions
    @petitions = Petition.page(params[:page])
  end

  def index
    load_all_petitions
    respond_to do |format|
       format.html
    end
  end

  def show
    respond_to do |format|
      format.html
    end
  end

  def update
    if petition_params[:accept]
      begin
        res = @petition.accept!
        res = "Accepted." if res === true
        flash[:notice] = (flash[:notice] || "") <<  (res ? res + " " : "")
      rescue ActiveRecord::RecordInvalid => e
        @petition.errors.add(:base, e.message)
        flash[:alert] = (flash[:alert] || "") << 'There was ane error accepting your petition: '
      end
    end
    if petition_params[:reject]
      begin
        res = @petition.reject!
        res = "Rejected." if res === true
        flash[:notice] = (flash[:notice] || "") <<  (res ? res + " " : "")
      rescue ActiveRecord::RecordInvalid => e
        @petition.errors.add(:base, e.message)
        flash[:alert] = (flash[:alert] || "") << 'There was ane error rejecting your petition: '
      end
    end
    if @petition.update(modify_date_inputs_on_params(petition_params).tap{ |ary| ary.delete('accept') }.tap{ |ary| ary.delete('reject') })
      flash[:notice] = (flash[:notice] || "") << "Saved #{@petition.to_label}"
    else
      flash[:alert] = (flash[:alert] || "") << "Petition could not be saved."

    end
    load_all_petitions
    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end



  def petition_params
    params.require(:petition).permit( [:user_id, :question1, :question2, :question3, :accepted_at, :rejected_at, :accept, :reject] )
  end

  def default_colspan
    6
  end

  def namespace
    "admin/" 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/petitions_controller.rb
class PetitionsController < ApplicationController
  helper :hot_glue
  include HotGlue::ControllerHelper

  before_action :authenticate_user!
  
  before_action :load_petition, only: [:show, :edit, :update, :destroy]
  after_action -> { flash.discard }, if: -> { request.format.symbol ==  :turbo_stream }



  

  



  def load_petition
    @petition = current_user.petitions.find(params[:id])
  end
  

  def load_all_petitions
    @petitions = current_user.petitions.page(params[:page])
  end

  def index
    load_all_petitions
    respond_to do |format|
       format.html
    end
  end

  def new 
    @petition = Petition.new(user: current_user)
   
    respond_to do |format|
      format.html
    end
  end

  def create
    modified_params = modify_date_inputs_on_params(petition_params.dup.merge!(user: current_user ) , current_user)
    @petition = Petition.create(modified_params)

    if @petition.save
      flash[:notice] = "Successfully created #{@petition.to_label}"
      load_all_petitions
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to petitions_path }
      end
    else
      flash[:alert] = "Oops, your petition could not be created."
      respond_to do |format|
        format.turbo_stream
        format.html
      end
    end
  end

  def show
    respond_to do |format|
      format.html
    end
  end

  def destroy
    begin
      @petition.destroy
    rescue StandardError => e
      flash[:alert] = "Petition could not be deleted"
    end
    load_all_petitions
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to petitions_path }
    end
  end

  def petition_params
    params.require(:petition).permit( [:answer1, :answer2, :answer3] )
  end

  def default_colspan
    3
  end

  def namespace
    ""
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/_errors.erb
<\%= turbo_frame_tag "errors" do %>
  <\% if resource.errors.any? %>
    <div id="error_explanation">
      <\% resource.errors.full_messages.each do |message| %>
        <div class="alert alert-danger">
          <\%= message %>
        </div>
      <\% end %>
    </div>
  <\% end %>
<\% end %>

app/views/admin/petitions/_errors.erb
<%= turbo_frame_tag "errors" do %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <% resource.errors.full_messages.each do |message| %>
        <div class="alert alert-danger">
          <%= message %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/admin/petitions/_form.erb
<div class="row">
  <div class='col form-group <%= 'alert-danger' if petition.errors.details.keys.include?(:user) %>' >
<%= f.collection_select(:user_id, User.all, :id, :name, {prompt: true, selected: @petition.user_id }, class: 'form-control') %>
<label class='small form-text text-muted'>User</label></div>
<div class="col form-group <%= 'alert-danger' if petition.errors.details.keys.include?(:question1) %>"><%= @petition.question1 %><label class='form-text'>Question1</label></div>
<div class="col form-group <%= 'alert-danger' if petition.errors.details.keys.include?(:question2) %>"><%= @petition.question2 %><label class='form-text'>Question2</label></div>
<div class="col form-group <%= 'alert-danger' if petition.errors.details.keys.include?(:question3) %>"><%= @petition.question3 %><label class='form-text'>Question3</label></div>
<div class='col form-group <%='alert-danger' if @petition.errors.details.keys.include?(:accepted_at)%>' > 
<%= datetime_field_localized(f, :accepted_at, petition.accepted_at, 'Accepted at', nil) %></div>
<div class='col form-group <%='alert-danger' if @petition.errors.details.keys.include?(:rejected_at)%>' > 
<%= datetime_field_localized(f, :rejected_at, petition.rejected_at, 'Rejected at', nil) %></div>

  <div class="">
    <%= link_to "Cancel", admin_petitions_path,  {class: "btn btn-secondary"} %>
    <%= f.submit "Save", class: "btn btn-primary pull-right" %>
  </div>
</div>

app/views/admin/petitions/_line.erb
<%= turbo_frame_tag "petition__#{ petition.id }" do  %>
  <div class='row scaffold-row' data-id='<%= petition.id %>' data-edit='false'>
    <%= render partial: 'admin/petitions/show', locals: { petition: petition } %>

  </div>
<% end %>

app/views/admin/petitions/_list.erb
<%= turbo_frame_tag "petitions-list"   do %>
  <div class="container-fluid scaffold-list">
    <h4>PETITIONS</h4>

    

    
    <div class="row scaffold-row">
      <div class='col'>User</div>
<div class='col'>Question1</div>
<div class='col'>Question2</div>
<div class='col'>Question3</div>
<div class='col'>Accepted at</div>
<div class='col'>Rejected at</div>
      

      

      <div class=' scaffold-col-heading scaffold-col-heading-buttons col-md-2' >

      </div>
    </div>

      <% if petitions.empty? %>
    <div>
        None
    </div>
      <% end %>
      <% petitions.each do |petition| %>
        <%= render partial: 'admin/petitions/line', locals: {petition: petition } %>
      <% end %>
    <% if petitions.respond_to?(:total_pages) %><%= paginate(petitions) %> <% end %>

    </div>
      
  </div>
<% end %>

app/views/admin/petitions/_new_button.erb
<%= turbo_frame_tag "petition-new" do %>
  <div>
    <%= link_to "New Petition",  new_admin_petition_path, disable_with: "Loading...", class: "new-petition-button btn btn-primary pull-right  " %>
  </div>
<% end %>

app/views/admin/petitions/_new_form.erb
<%= turbo_frame_tag "petition-new" do %>
<h3>
  New Petition
  </h3>
  <%= form_with model:  petition, url: admin_petitions_path(), method: "post" do  |f| %>
    <%=  render partial: "admin/petitions/form", locals: { petition:  petition, f: f} %>
  <% end %>
<% end %>

app/views/admin/petitions/_show.erb
<div class='col'>
  <%= petition.user.try(:name) || '<span class="content alert-danger">MISSING</span>'.html_safe %>
</div>
<div class='col'>
  <%= petition.question1 %>
</div>
<div class='col'>
  <%= petition.question2 %>
</div>
<div class='col'>
  <%= petition.question3 %>
</div>
<div class='col'   >
  <% unless petition.accepted_at.nil? %>
<%= petition.accepted_at.in_time_zone(current_timezone).strftime('%m/%d/%Y @ %l:%M %p ') + timezonize(current_timezone) %>
<% else %>
<span class='alert-danger'>MISSING</span>
<% end %>
</div>
<div class='col'   >
  <% unless petition.rejected_at.nil? %>
<%= petition.rejected_at.in_time_zone(current_timezone).strftime('%m/%d/%Y @ %l:%M %p ') + timezonize(current_timezone) %>
<% else %>
<span class='alert-danger'>MISSING</span>
<% end %>
</div>




<div class="col scaffold-line-buttons  col-md-2" >
  


  <%= form_with model: petition, url: admin_petition_path(petition) do |f| %>
      <%= f.hidden_field :accept, value: "accept" %>
    <%= f.submit 'Accept'.html_safe, disabled: (petition.respond_to?(:acceptable?) && ! petition.acceptable? ), data: {confirm: 'Are you sure you want to accept this petition?'}, class: 'petition-button btn btn-primary ' %>
    <% end %>
<%= form_with model: petition, url: admin_petition_path(petition) do |f| %>
      <%= f.hidden_field :reject, value: "reject" %>
    <%= f.submit 'Reject'.html_safe, disabled: (petition.respond_to?(:rejectable?) && ! petition.rejectable? ), data: {confirm: 'Are you sure you want to reject this petition?'}, class: 'petition-button btn btn-primary ' %>
    <% end %>

  
</div>

app/views/admin/petitions/create.turbo_stream.erb
<% if @petition.errors.none? %>
  <%= turbo_stream.replace "petitions-list" do %>
  <%= render partial: "list", locals: {petitions: @petitions} %>
  <% end %>
  <% end %>
  <%= turbo_stream.replace "petition-new" do %>
  <% if @petition.errors.none? %>
  <%= render partial: "new_button", locals: {} %>
  <% else %>
  <%= render partial: "new_form", locals: {petition: @petition  } %>
  <% end %>
  <% end %>
  <%= turbo_stream.replace "flash_notices" do %>
  <%= render partial: "layouts/flash_notices" %>
  <% if @petition.errors.any? %>
  <%= render partial: "errors", locals: {resource: @petition} %>
  <% end %>
<% end %>

app/views/admin/petitions/destroy.turbo_stream.erb
<%= turbo_stream.replace "petitions-list" do %>
  <%= render partial: "list", locals: {petitions: @petitions  }  %>
<% end %>

app/views/admin/petitions/edit.erb
<%= link_to "<i class='fa fa-arrow-circle-left  2x'></i> Back to list".html_safe, admin_petitions_path %>

<%= turbo_frame_tag "petition__#{@petition.id}" do  %>

  <div class="cell editable" style="position: relative;">

    <% if @petition.errors.any? %>
      <%= render(partial: "admin/errors", locals: {resource: @petition }) %>
    <% end %>

    <h2>Editing <%= @petition.to_label %></h2>
    <%= form_with model: @petition, url: admin_petition_path(@petition) do |f| %>
    <%=  render partial: "form",  locals: {:petition => @petition, f: f} %>
    <% end %>

  </div>

<% end %>

app/views/admin/petitions/edit.turbo_stream.erb
<%= turbo_stream.replace "petition__#{@petition.id}" do %>
  <%= render 'edit' %>
<% end %>

app/views/admin/petitions/index.erb
<div class="container-fluid">
  <div class="row"> <div class="col-md-12">
  

  <div class="clearfix"></div>
  <%= render partial: 'admin/petitions/list',
    locals: {petitions: @petitions } %>

  </div></div>
</div>

app/views/admin/petitions/new.erb
<%= render partial: "new_form", locals: {petition: @petition} %>

app/views/admin/petitions/update.turbo_stream.erb
<%= turbo_stream.replace "petitions-list" do %>
  <%= render partial: 'admin/petitions/list', locals: {petitions: @petitions } %>
<% end %>


<%= turbo_stream.replace "flash_notices" do %>
  <%= render partial: "layouts/flash_notices" %>
  <% if @petition.errors.any? %>
  <%= render partial: "errors", locals: {resource: @petition} %>
  <% end %>
<% end %>

app/views/layouts/_flash_notices.erb
<%= turbo_frame_tag "flash_notices" do %>
  <% unless notice.nil? %>
    <div class="alert alert-notice alert-dismissible">
      <%= notice %>
    </div>
  <% end %>
  <% unless alert.nil? %>
    <div class="alert alert-danger alert-dismissible">
      <%= alert %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetitionApprovalableSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render partial: 'layouts/flash_notices' %>

  <%= yield %>



  <br />
  <br />
  <br />
  <% if current_user %>
    <%= button_to "Log Out", destroy_user_session_path, method: :delete, 'data-turbo': false %>
  <% end %>
  </body>
</html>

app/views/petitions/_form.erb
<div class="row">
  <div class="col form-group #{'alert-danger' if petition.errors.details.keys.include?(:answer1)}"><%= f.text_area :answer1, class: 'form-control', autocomplete: 'off', cols: 40, rows: '5' %><label class='form-text'>Answer1</label></div>
<div class="col form-group #{'alert-danger' if petition.errors.details.keys.include?(:answer2)}"><%= f.text_area :answer2, class: 'form-control', autocomplete: 'off', cols: 40, rows: '5' %><label class='form-text'>Answer2</label></div>
<div class="col form-group #{'alert-danger' if petition.errors.details.keys.include?(:answer3)}"><%= f.text_area :answer3, class: 'form-control', autocomplete: 'off', cols: 40, rows: '5' %><label class='form-text'>Answer3</label></div>

  <div class="">
    <%= link_to "Cancel", petitions_path,  {class: "btn btn-secondary"} %>
    <%= f.submit "Save", class: "btn btn-primary pull-right" %>
  </div>
</div>

app/views/petitions/_line.erb
<%= turbo_frame_tag "petition__#{ petition.id }" do  %>
  <div class='row scaffold-row' data-id='<%= petition.id %>' data-edit='false'>
    <%= render partial: 'petitions/show', locals: { petition: petition } %>

  </div>
<% end %>

app/views/petitions/_list.erb
<%= turbo_frame_tag "petitions-list"   do %>
  <div class="container-fluid scaffold-list">
    

    <%= render partial: "petitions/new_button", locals: {}%>

    
  </div>
<% end %>

app/views/petitions/_new_button.erb
<%= turbo_frame_tag "petition-new" do %>
  <div>
    <%= link_to "New Petition",  new_petition_path, disable_with: "Loading...", class: "new-petition-button btn btn-primary pull-right  " %>
  </div>
<% end %>

app/views/petitions/_new_form.erb
<%= turbo_frame_tag "petition-new" do %>
<h3>
  New Petition
  </h3>
  <%= form_with model:  petition, url: petitions_path(), method: "post" do  |f| %>
    <%=  render partial: "petitions/form", locals: { petition:  petition, f: f} %>
  <% end %>
<% end %>

app/views/petitions/_show.erb
<div class='col'>
  <%= petition.answer1 %>
</div>
<div class='col'>
  <%= petition.answer2 %>
</div>
<div class='col'>
  <%= petition.answer3 %>
</div>




<div class="col scaffold-line-buttons  col-md-2" >
  
    <%= form_with url: petition_path(petition), html: {style: "display: inline-block;"}, method: :delete do |f| %>
      <%= f.submit "Delete".html_safe,  data: {confirm: 'Are you sure?'}, class: "delete-petition-button btn btn-primary btn-sm" %>
    <% end %>
  


  

  
</div>

app/views/petitions/edit.erb
<%= link_to "<i class='fa fa-arrow-circle-left  2x'></i> Back to list".html_safe, petitions_path %>

<%= turbo_frame_tag "petition__#{@petition.id}" do  %>

  <div class="cell editable" style="position: relative;">

    <% if @petition.errors.any? %>
      <%= render(partial: "errors", locals: {resource: @petition }) %>
    <% end %>

    <h2>Editing <%= @petition.to_label %></h2>
    <%= form_with model: @petition, url: petition_path(@petition) do |f| %>
    <%=  render partial: "form",  locals: {:petition => @petition, f: f} %>
    <% end %>

  </div>

<% end %>

app/views/petitions/index.erb
<div class="container-fluid">
  <div class="row"> <div class="col-md-12">
  

  <div class="clearfix"></div>
  <%= render partial: 'petitions/list',
    locals: {petitions: @petitions } %>

  </div></div>
</div>

app/views/petitions/update.turbo_stream.erb
<%= turbo_stream.replace "petition__#{@petition.id}" do %>
  <%= render partial: 'line', locals: {petition: @petition  } %>
<% end %>

<%= turbo_stream.replace "flash_notices" do %>
  <%= render partial: "layouts/flash_notices" %>
  <% if @petition.errors.any? %>
  <%= render partial: "errors", locals: {resource: @petition} %>
  <% end %>
<% end %>